version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - "${FLASK_APP_DOCKER_HOST_PORT}:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'teko-first-project'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '${MYSQL_DOCKER_HOST_PORT}:3306'
