LOGIN_ACTION = 0
REGISTER_ACTION = 1
PASSWORD_CHANGE_ACTION = 2
PASSWORD_RESET_ACTION = 3

ACTION_SEND_MAIL = "SEND_MAIL"

SIGNAL_NOTHING = "NOTHING"
SIGNAL_CAPTCHA = "CAPTCHA"
SIGNAL_ACCOUNT_LOCK = "ACCOUNT_LOCK"


LIMIT_CAPTCHA = 3
LIMIT_ACCOUNT_LOCK = 5

TIME_ACCOUNT_LOCK = 900
TIME_ACCOUNT_LOCK_DURATION = 600


PASSWORD_CHANGE_SUCCESS = 0
PASSWORD_CHANGE_FAILED = 1
PASSWORD_CHANGE_LAST_FIVE_PASSWORDS = 2
PASSWORD_CHANGE_VALIDATION_FAILED = 3
PASSWORD_CHANGE_PRIVILEGE_FAILED = 4


REGISTER_SUCCESS = 0
REGISTER_DUPLICATED_USERNAME_OR_EMAIL = 1
REGISTER_VALIDATION_FAILED = 2


LOCK_ACCOUNT_SUCCESS = 0
LOCK_ACCOUNT_FAILED_PRIVILEGE = 1
LOCK_ACCOUNT_FAILED_LOCKED_ALREADY = 2


UNLOCK_ACCOUNT_SUCCESS = 0
UNLOCK_ACCOUNT_NOT_BEING_LOCKED_FAILED = 1


DELETE_ACCOUNT_SUCCESS = 0
DELETE_ACCOUNT_FAILED_PRIVILEGE = 1

ADMIN_PRIVILEGE = 'admin'
